### PR TITLE
Chord keymaps

### LINKED ISSUE #18: Broken in new Obsidian live preview editor
**the problem**
leader key recognition lost in the now new standard Obsidian "live preview editor"

**To Reproduce**
switching back to  legacy editor restores leader key functionality

**context**
 - OS: macOS monterey
 - Obsidian Version: 13.24
 - Leader Hotkeys Version: 0.1.3

### PR DESCRIPTION
**Pull request by canelhasmateus**
Enables use of arbitrary length keybindings. 
Fixes #18

### CODE REVIEW

**Comment by canelhasmateus** [comment]
Still a bunch of things left to do.
The current implementation is not backwards compatible . it should be simple to add a conversion , however.
Some places left me confused, such as the key-modifier implementation, which is currently incomplete ( alt modifier does not exists, not sure how to handle ctrl vs win vs cmd , don't know what meta even means )
Not sure how to handle other currently opened issues, such as #17 ;
Since i'm registering dom events directly on the workspace ( as a fix for #18 ) , there are some conflict problems: In my setup, ctrl + b is bounded to something else: Therefore the editor handles it before i have the oportunity to.
Still left to do is change the peripheral components accordingly to the interface changes.

**Comment by canelhasmateus** [comment]
The peripheral components, such as the settings tab and the register modal have been changed accordingly. I opted for a 'bigger' change here to be able to create a independent modal. This makes it so i can register the modal opening as a command, which gives a hotkey to map more hotkeys. 

As far as key-handling goes, i mostly figured it out . However , mac compatibility, as well as international keyboards are left to be investigated.

What is left is backwards-compatibility ( simple ). There are also other considerations to be done, such as the effect of binding directly to the document, and the repercussions thereof ( conflicts and scoped/context-aware hotkeys).
Some refactors are also due.

**Comment by canelhasmateus** [comment]
Big Refactor done, and i believe the code has arrived close to its final state.

Issues still remaining:
      mac compatibility, as well as international keyboards
       backwards-compatibility
       Validation during creation
       understanding the effect and repercussions of binding directly to the document

Are you still interested in this project? If so, mind commenting on the code or the points listed above?

File: src/main.ts [hunk 1]
```diff
@@ -7,479 +7,1026 @@ import {
...
-    this.setNewKey = setNewKey;
+  public constructor(parent: LeaderHotkeys) {
+    this.parent = parent;
+    this.setKeymap(parent.settings.hotkeys);
   }
 
-  public onOpen = (): void => {
-    const { contentEl } = this;
+  public readonly handleKeyDown = (event: KeyboardEvent): void => {
+    console.log(event);
```
Comment (tgrosinger) [inline src/main.ts:429]: We should probable remove this. Seems to log every key stroke in Obsidian right now.

File: src/main.ts [hunk 2]
```diff
@@ -7,479 +7,1026 @@ import {
...
+  if (!bestMatch) {
+    return MatchKind.NoMatch;
+  }
+  if (bestMatch.isLeaf()) {
+    return MatchKind.FullMatch;
+  }
+  return MatchKind.PartialMatch;
+};
+const defaultHotkeys: KeyMap[] = [
+  new KeyMap('editor:focus-left', [KeyPress.ctrl('b'), KeyPress.just('h')]),
```
Comment (tgrosinger) [inline src/main.ts:1001]: Do these defaults work? Or does the live preview steal them? If they don't we should pick a new default leader.

File: src/main.ts [hunk 3]
```diff
@@ -7,479 +7,1026 @@ import {
...
+    const setting = new Setting(this.contentEl);
+
+    setting.addDropdown((dropdown) => {
+      dropdown.selectEl.addClass('leader-hotkeys-command');
+
+      for (const command of this.parent.obsidianCommands()) {
+        dropdown.addOption(command.id, command.name);
+      }
+
+      const placeHolder = new Option('Select a Command', 'placeholder', true);
```
Comment (tgrosinger) [inline src/main.ts:721]: It would be nice to have an informative title above this input.

File: src/main.ts [hunk 4]
```diff
@@ -7,479 +7,1026 @@ import {
...
+          this.close();
+        }
     }
+  };
+
+  private readonly renderKeyPresses = (elements: HTMLElement[]): void => {
+    this.contentEl.empty();
+
+    const header = document.createElement('p');
+    header.setText(`Registering for ${this.commandId}`);
```
Comment (tgrosinger) [inline src/main.ts:689]: It would be nice to have an informative title above this. It was unclear to me at first what was expected of me here.

It would also be nice to be able to finish the command sequence by clicking a "Save" button or something..

**Review by tgrosinger — COMMENTED** [review]
I like what has been done here. It seems way more powerful than what I had previously. I'm having a lot of trouble getting it to work though. I have setup a couple of shortcuts using `ctrl-,` as my leader key, and I can see in the logs that a Keyboard event for `{ctrlKey: true, key: ','}` is being registered, but it says `EmptyMatch`. I'm testing in LivePreview mode, in case that makes a difference.

Thanks!s

File: src/main.ts (hunk 4 above)
Comment (canelhasmateus) [reply src/main.ts:689]: A informative would be nice here. I tend to skimp on UI , sorry about that haha
Do you think a Save button is necessary? Were you able to complete the command using the 'enter' key, and following the suggestions?

File: src/main.ts (hunk 2 above)
Comment (canelhasmateus) [reply src/main.ts:1001]: They do work, assuming no conflicting keybinds. The 'proper' ones, mapped via the native plugin seem to take precedence. In these cases, i don't even receive the keyboard event.

**Comment by canelhasmateus** [comment]
In the end, did you manage to trigger your command? 
Note that in the current form , i don't have retro-compatibility, so for them to work properly, you should re-register them.

Also note that I ended up removing the 'enter leader key mode' command, since with the current setup, you can just map whatever combination you want. This might be the point you're hitting,

**Comment by canelhasmateus** [comment]
Noticed a bug when updating commands: It adds a new one instead of updating. Will submit a fix soon enough.

**Comment by canelhasmateus** [comment]
Jolting down a idea that came to my head, about how to handle the events.

The flow would be like this:

On init, we wouldn't have the registerEventHandler( ' keydown') directly on the dom anymore.

When the user creates a new keymap ( using the modal) , we check the first key of the sequence.
If it is one that we hadn't seen before, we dynamically create a command that maps that keydown to a callback that goes like 
``` 
callback = () => { 
let syntethicKey = new KeyPress( firstKeyOfTheRecordingSequence ) ; 
matcher.advance( syntheticKey) 
}

this way we can basically keep the functionality, and still play by the application rules.
Of course, we do every validation and handling for duplicates etc before doing the registration

File: src/main.ts (hunk 4 above)
Comment (tgrosinger) [reply src/main.ts]: It took me a while to figure out that pressing a special key followed by another key combo would save. I think adding a Save and Cancel pair of buttons would definitely help make the UI easier to use. Leaving the key combo too is great though, there can be more than one way to save it.

**Comment by tgrosinger** [comment]
> In the end, did you manage to trigger your command? Note that in the current form , i don't have retro-compatibility, so for them to work properly, you should re-register them.
> 
> Also note that I ended up removing the 'enter leader key mode' command, since with the current setup, you can just map whatever combination you want. This might be the point you're hitting,

I started from a fresh Vault and mapped new short cuts. I did have it work a couple times, but it was very inconsistent and most of the time did not work.

File: src/main.ts (hunk 4 above)
Comment (canelhasmateus) [reply src/main.ts]: I've added the save button, will add the cancel too, nice heads up.

**Comment by canelhasmateus** [comment]
> I started from a fresh Vault and mapped new short cuts. I did have it work a couple times, but it was very inconsistent and most of the time did not work.

With the current setup, it should only work while having a file open. The other approach i described above should make it work independently. 
Can you check it that is the source of the inconsistencies? If not, can you get me the log of what is happening?

> I'm not quite sure what you're describing. Would this be something displayed when commands are being created, or while being used? 

While being used. i'm referring to something like https://raw.githubusercontent.com/liuchengxu/img/master/vim-which-key/vim-which-key.png ; 
But lets start small, shall we?

**Comment by canelhasmateus** [comment]
Noticed a bug in regards to the keypress consistency. I blame my last-hour refactor, along with my lack of tests :P.
Could you try again? should be more consistent now.

**Comment by tgrosinger** [comment]
> Noticed a bug in regards to the keypress consistency. I blame my last-hour refactor, along with my lack of tests :P. Could you try again? should be more consistent now.

Hey, sorry for the long delay. Let me give it another shot now!

**Comment by tgrosinger** [comment]
Working great for me now. Thank you!

**Comment by Ampa** [comment]
Wow! This is a major upgrade!
Thank you canelhasmateus and tgrosinger.

**Comment by canelhasmateus** [comment]
> Wow! This is a major upgrade! Thank you canelhasmateus and tgrosinger.

This wasn't done with the amount of care and love that i would like, but it is still pretty good. 
Don't be shy to file in any issues you find , and thank you for your kind words, @Ampa .
